upload @eshanized push script

diff --git a/eshanized b/eshanized
--- a/eshanized
+++ b/eshanized
@@ -1,1 +1,35 @@
 #!/bin/bash
+
+#!/bin/bash
+
+# Author            : Eshan Roy
+# Author URI        : https://eshanized.github.io
+
+# NOTE: Run this at your own risk! 
+
+# GitHub repository URL
+REPO_URL="https://github.com/IXINTL/MindMapp-Documentation.git"
+
+# Check if there are any changes to commit
+if [[ -n $(git status -s) ]]; then
+    # Add all changes to the staging area
+    git add .
+
+    # Prompt user for commit message
+    read -p "Enter commit message: " COMMIT_MESSAGE
+
+    # Commit changes with a default message
+    git commit -m "$COMMIT_MESSAGE"
+
+    # Push changes to the remote repository
+    # git push $REPO_URL
+
+    # Check if the push was successful
+    if [ $? -eq 0 ]; then
+        echo "Push successful!"
+    else
+        echo "Error: Push failed!"
+    fi
+else
+    echo "No changes to commit."
+fi
